version: '2.0'
services:
  collab-sketch:
    image: srujankumar/collab-sketch:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/certs:/etc/nginx/certs
      - /app/db:/app/db
    environment:
      - WORDS=${WORDS}
